repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [--line-length=150]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=150
          - --ignore=E203,E266,E501,W503,F401,E402,E731
          - --per-file-ignores=__init__.py:F401,F403

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --config-data
          - |
            extends: default
            rules:
              line-length:
                max: 150
              truthy: disable
              document-start: disable
              braces:
                min-spaces-inside: 0
                max-spaces-inside: -1
              comments:
                min-spaces-from-content: 1

  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        args: ["--style", "{column_limit: 150, align_closing_bracket_with_visual_indent: true, dedent_closing_brackets: true}"]
